[versions]
# The latest versions are available at https://fabricmc.net/develop
minecraft = "1.21.1"
fabric_loader = "0.16.10"
fabric_api = "0.115.1+1.21.1"
fabric_language_kotlin = "1.13.1+kotlin.2.1.10"
softer_pastels = "0.9.3-rev.9f22720"
sodium = "mc1.21.1-0.6.9-fabric"
continuity = "3.0.0+1.21"
mod_menu = "11.0.3"
emi = "1.1.20+1.21.1+fabric"
worldgen_devtools = "1.1.0+1.21.1"
debugutils = "1.21-1.0.6"
modonomicon = "1.114.0"
fcapi = "21.1.3"
flywheel = "1.0.2"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
fabric_language_kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric_language_kotlin" }
softer_pastels = { module = "one.devos.nautical:softerpastels", version.ref = "softer_pastels" }
sodium = { module = "maven.modrinth:sodium", version.ref = "sodium" }
continuity = { module = "maven.modrinth:continuity", version.ref = "continuity" }
mod_menu = { module = "com.terraformersmc:modmenu", version.ref = "mod_menu" }
emi = { module = "maven.modrinth:emi", version.ref = "emi" }
worldgen_devtools = { module = "maven.modrinth:worldgen-devtools", version.ref = "worldgen_devtools" }
debugutils = { module = "maven.modrinth:debugutils", version.ref = "debugutils" }
modonomicon = { module = "com.klikli_dev:modonomicon-1.21.1-fabric", version.ref = "modonomicon" }
fcapi = { module = "fuzs.forgeconfigapiport:forgeconfigapiport-fabric", version.ref = "fcapi" }
flywheel-api = { module = "dev.engine-room.flywheel:flywheel-fabric-api-1.21.1", version.ref = "flywheel" }
flywheel = { module = "dev.engine-room.flywheel:flywheel-fabric-1.21.1", version.ref = "flywheel" }

# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
[bundles]
dev_mods = [ "sodium", "emi", "worldgen_devtools", "debugutils" ]
dependencies = [ "mod_menu", "softer_pastels", "continuity" ]

[plugins]
grgit = { id = "org.ajoberstar.grgit", version = "5.2.1"}
fabric_loom = { id = "fabric-loom", version = "1.10-SNAPSHOT" }

