[versions]
# The latest versions are available at https://fabricmc.net/develop
minecraft = "1.20.4"
fabric-loader = "0.15.6"

fabric-api = "0.95.4+1.20.4"
fabric_language_kotlin = "1.10.17+kotlin.1.9.22"

softer_pastels = "0.5.0-rev.19755f8"

sodium_version = "mc1.20.4-0.5.8"
mod_menu_version = "9.0.0"
joml_version = "1.10.5"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric_language_kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric_language_kotlin" }

softer_pastels = { module = "one.devos.nautical:SofterPastels", version.ref = "softer_pastels" }

sodium = { module = "maven.modrinth:sodium", version.ref = "sodium_version" }
joml = { module = "org.joml:joml", version.ref = "joml_version" }
mod_menu = { module = "com.terraformersmc:modmenu", version.ref = "mod_menu_version" }

# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
[bundles]
dev_mods = [ "joml", "sodium" ]
dependencies = [ "mod_menu", "softer_pastels" ]

[plugins]
grgit = { id = "org.ajoberstar.grgit", version = "5.2.1"}
fabric_loom = { id = "fabric-loom", version = "1.5-SNAPSHOT" }

