name: build
on: [ pull_request, push ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PUBLISH_SUFFIX: snapshots
      MAVEN_USER: ${{ secrets.MAVEN_USER }}
      MAVEN_PASS: ${{ secrets.MAVEN_PASS }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK (Java 21)
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Loom Cache
        uses: actions/cache@v4
        with:
          path: "**/.gradle/loom-cache"
          key: "${{ runner.os }}-gradle-${{ hashFiles('**/libs.versions.*', '**/*.gradle*', '**/gradle-wrapper.properties') }}"
          restore-keys: "${{ runner.os }}-gradle-"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: gradlew Permission Grant
        run: chmod +x gradlew

      - name: Build w/ Gradle
        run: ./gradlew buildOrPublish

      - name: Capture Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/